### PR TITLE
Allow update expressions

### LINKED ISSUE #6: assigning to r value
```js
| 
| var getId = exports.getId = function getId() {
|   return globalGetInterceptor(global, "id")++;
| };
```

So, this is the error, not really sure how to fix it

original code:
```js
export const global = {
  id: 0
}

export const getId = (): number => global.id++

```

### PR DESCRIPTION
**Pull request by zwhitchcox**
Fixes #6

### CODE REVIEW

**Comment by zwhitchcox** [comment]
So, this branch is forked from my other PR, so probably want to look at that one first

This allows update expressions...also, updates some dependencies that I thought might be the cause of a problem I was having...turned out to be unrelated, but left the updated dependencies, because why not?

**Comment by wbern** [comment]
@krzkaczor Would love to have these PR's merged, along with issue #9 resolved!

**Comment by MarekGubiec** [comment]
@krzkaczor Me as well ^^

**Comment by krzkaczor** [comment]
@MarekGubiec sorry but this is abandonware at this point. You need to maintain your own fork for support. Also take a look at npm because I am under impression that someone pushed fixed version there....

**Pull request closed without merging**
